#1. docker-compose -p microservices-comp3095-ecommerce -f docker-compose-single.yml up -d
    # -- This command will start the containers in detached mode without rebuilding the images (if they already exist)




services:

  api-gateway:
    image: api-gateway
    ports:
      - "9000:9000"
    build:
      context: ./api-gateway   # The directory where the Dockerfile resides
      dockerfile: ./Dockerfile     # Specify the Dockerfile for use to build the image
    container_name: api-gateway
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - product-service
      - order-service
      - inventory-service
    networks:
      - spring

  product-service:
    image: product-service
    ports:
      - "8084:8084"
    build:
      context: ./product-service   # The directory where the Dockerfile resides
      dockerfile: ./Dockerfile     # Specify the Dockerfile for use to build the image
    container_name: product-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - mongo
    networks:
      - spring

  order-service:
    image: order-service
    ports:
      - "8085:8085"
    build:
      context: ./order-service   # The directory where the Dockerfile resides
      dockerfile: ./Dockerfile     # Specify the Dockerfile for use to build the image
    container_name: order-service
    environment:
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      - postgres-order
    networks:
      - spring

  inventory-service:
    image: inventory-service
    ports:
      - "8086:8086"
    build:
      context: ./inventory-service   # The directory where the Dockerfile resides
      dockerfile: ./Dockerfile     # Specify the Dockerfile for use to build the image
    container_name: inventory-service
    environment:
     - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-inventory:5432/inventory-service
     - SPRING_DATASOURCE_USERNAME=admin
     - SPRING_DATASOURCE_PASSWORD=password
     - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - postgres-inventory
    networks:
      - spring

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=password
    volumes:
      - ./data/mongo/products:/data/db
      - ./init/mongo/docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    container_name: mongo
    networks:
      - spring

  mongo-express:
    image: mongo-express
    ports:
      - "8081:8081"
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=password
      - ME_CONFIG_MONGODB_SERVER=mongo
     # - ME_CONFIG_MONGODB_AUTH_DATABASE=admin
    container_name: mongo-express
    depends_on:
      - mongo
    networks:
      - spring

  postgres-inventory:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    container_name: postgres-inventory
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=inventory-service

    volumes:
      - ./data/inventory:/var/lib/postgresql/data
      - ./init/postgres/inventory/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - spring



  postgres-order:
    image: postgres
    ports:
      - "5433:5433"
    container_name: postgres-order
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=order-service
    command: -p 5433
    volumes:
      - ./data/order:/var/lib/postgresql/data
      - ./init/postgres/order/init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - spring

  keycloak:
    container_name: keycloak
    hostname: keycloak
    image: quay.io/keycloak/keycloak:24.0.1
    command: [ "start-dev", "--http-port=8089","--import-realm" ]
    environment:
      DB_VENDOR: postgres
      DB_ADDR: postgres-keycloak
      DB_DATABASE: keycloak
      DB_USER: admin
      DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      ROOT_LOGLEVEL: DEBUG
      JBOSS_LOG_MANAGER_ROOT_LOGGER: DEBUG, stout, FILE
    ports:
      - "8089:8089"
    volumes:
      - ./realms/:/opt/keycloak/data/import
    depends_on:
      - postgres-keycloak
    networks:
      - spring

  postgres-keycloak:
    image: postgres
    ports:
      - "5431:5431"
    command: -p 5431
    container_name: postgres-keycloak
    environment:
      - POSTGRES_DB=keycloak
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=password
      - PGDATA=/data/postgres
    volumes:
      - ./data/postgres/keycloak:/var/lib/postgresql/data
    networks:
      - spring

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "8888:80"
    container_name: pgadmin-single
    environment:
      - PGADMIN_DEFAULT_EMAIL=user@domain.ca
      - PGADMIN_DEFAULT_PASSWORD=password
    networks:
      - spring

volumes:
  mongo-db:
      driver: local


networks:
  spring:
    driver: bridge
